name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup FoundationDB
      uses: foundationdb-rs/foundationdb-actions-install@v2.1.0
      with:
        version: "7.3.27"
    - name: Setup buf
      uses: bufbuild/buf-setup-action@v1.40.1
    - name: Setup protoc
      run: sudo apt-get install protobuf-compiler
    - name: Generate buf
      run: cd crates/valv && buf generate
    - name: Build
      run: cargo build
    - name: Run Valv tests
      run: cargo test -p valv
    - name: Run KMS server and integration tests
      run: |
        cd examples/google-kms && cargo run &
        SERVER_PID=$!
        sleep 1
        cargo test -- --nocapture
        kill $SERVER_PID

